### ISSUE TITLE
Issues about loading images features, which leads to inconsistent feature dimensions

### ISSUE THREAD

**Issue by he159ok** [githwd2016/MATE#3]
When I run your training after filling some parameters for the configure-json file, there is an issue in loading image features, which leads to inconsistent dimensions, as below,

[
Traceback (most recent call last):
  File "/home/jfhe/Documents/daily software/pycharm/pycharm-professional-anaconda-2019.1.1/pycharm-anaconda-2019.1.1/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/jfhe/Documents/daily software/pycharm/pycharm-professional-anaconda-2019.1.1/pycharm-anaconda-2019.1.1/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/jfhe/Documents/daily software/pycharm/pycharm-professional-anaconda-2019.1.1/pycharm-anaconda-2019.1.1/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/jfhe/Documents/daily software/pycharm/pycharm-professional-anaconda-2019.1.1/pycharm-anaconda-2019.1.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/jfhe/Documents/MountHe/jfhe/mm_dialogue/MM_Dialogue/train.py", line 268, in <module>
    exit(main(_args))
  File "/home/jfhe/Documents/MountHe/jfhe/mm_dialogue/MM_Dialogue/train.py", line 167, in main
    dec_output_prob = model_p((text_input, text_pos, text_turn, text_speaker,
  File "/home/jfhe/anaconda3/envs/MM20/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jfhe/anaconda3/envs/MM20/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/jfhe/anaconda3/envs/MM20/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jfhe/Documents/MountHe/jfhe/mm_dialogue/MM_Dialogue/widget/model.py", line 83, in forward
    context_embs, context_seq = self.context_encode(context)
  File "/home/jfhe/Documents/MountHe/jfhe/mm_dialogue/MM_Dialogue/widget/model.py", line 88, in context_encode
    text_embs, image_embs = self.emb(text_input, text_pos, text_turn, text_speaker,
  File "/home/jfhe/anaconda3/envs/MM20/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jfhe/Documents/MountHe/jfhe/mm_dialogue/MM_Dialogue/widget/module.py", line 60, in forward
    image_outputs = self.image_layer(image_input) + self.src_token_emb(image_turn) + \
RuntimeError: The size of tensor a (12) must match the size of tensor b (24) at non-singleton dimension 1
import sys; print('Python %s on %s' % (sys.version, sys.platform))
Python 3.8.10 (default, May 19 2021, 18:05:58) 
[GCC 7.3.0] on linux
image_input.shape
torch.Size([1, 12, 4096])
image_turn.shape
torch.Size([1, 24])
image_speaker.shape
torch.Size([1, 24])
image_pos.shape
torch.Size([1, 24])](url)

The code is from (widget/module.py/class Eb) as below `[    def forward(self, src_input, src_pos, src_turn, src_speaker,
                image_input, image_pos, image_turn, image_speaker):
        # text_input, text_pos, text_turn, text_speaker, image_turn, image_speaker = (bs, text_len)
        # image_input = (bs, image_len, image_in_size)
        text_outputs = self.src_token_emb(src_input) + self.src_token_emb(src_turn) + \
                       self.src_token_emb(src_speaker) + self.position_enc(src_pos)
        # (bs, text_len, embedding_size)
        image_outputs = self.image_layer(image_input) + self.src_token_emb(image_turn) + \
                        self.src_token_emb(image_speaker) + self.src_token_emb(image_pos)
        # (bs, image_len, embedding_size)
        return text_outputs, image_outputs](url)`, where the four items cannot sum up due to in consistent feature dimensions.

**Comment by githwd2016** [comment]
I have fix the bug, please try again.

**Comment by he159ok** [comment]
Hi, the bug still exists. It is a very strange one. 
Concretely, since the issue is 
"
Traceback (most recent call last):
  File "/home/jfhe/anaconda3/envs/MM20/lib/python3.8/pdb.py", line 1705, in main
    pdb._runscript(mainpyfile)
  File "/home/jfhe/anaconda3/envs/MM20/lib/python3.8/pdb.py", line 1573, in _runscript
    self.run(statement)
  File "/home/jfhe/anaconda3/envs/MM20/lib/python3.8/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/jfhe/Documents/MountHe/jfhe/mm_dialogue/MM_Dialogue/train.py", line 267, in <module>
    exit(main(_args))
  File "/home/jfhe/Documents/MountHe/jfhe/mm_dialogue/MM_Dialogue/train.py", line 166, in main
    dec_output_prob = model((text_input, text_pos, text_turn, text_speaker,
  File "/home/jfhe/anaconda3/envs/MM20/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jfhe/Documents/MountHe/jfhe/mm_dialogue/MM_Dialogue/widget/model.py", line 83, in forward
    context_embs, context_seq = self.context_encode(context)
  File "/home/jfhe/Documents/MountHe/jfhe/mm_dialogue/MM_Dialogue/widget/model.py", line 88, in context_encode
    text_embs, image_embs = self.emb(text_input, text_pos, text_turn, text_speaker,
  File "/home/jfhe/anaconda3/envs/MM20/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jfhe/Documents/MountHe/jfhe/mm_dialogue/MM_Dialogue/widget/module.py", line 64, in forward
    image_outputs = self.image_layer(image_input) + self.src_token_emb(image_turn) + \
RuntimeError: The size of tensor a (12) must match the size of tensor b (24) at non-singleton dimension 1
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
"
where I believe the issue comes from the inconsistent shapes of `image_input`, `image_turn`, `image_speaker` and `image_pos` for the 25th entry (index = 530339) if we set the batch_size as 1 rather than 32. These 4 items are in your "widget/data.py/class EB". I add the below rows in your widget/data/__getitem__ to print the results,
`
            print("img", img)
            print("img_length", img_length)
            print("speaker", speaker)
            image_input.extend(self.get_imgs(img))
`. Then, I get below outputs, 

2021-06-03 20:48:21,160 - train.py[line:180] - INFO: Epoch [1], Batch [22], Loss: 10.0622, Perplexity: 23440.01974, Accuracy: 0.000 %
23
455145
img []
img_length 0
speaker <pad>
image_input_length 0
img ['', '', '', '', '', '', '', '', '', '', '', '']
img_length 0
speaker @user
image_input_length 12
torch.Size([1, 24, 512])
torch.Size([1, 24, 512])
torch.Size([1, 24, 512])
torch.Size([1, 24, 512])
2021-06-03 20:48:21,285 - train.py[line:180] - INFO: Epoch [1], Batch [23], Loss: 9.84369, Perplexity: 18839.16685, Accuracy: 7.143 %
24
1239138
img ['', '', '', '', '', '', '', '', '', '', '', '']
img_length 0
speaker @system
image_input_length 12
img ['', '', '', '', '', '', '', '', '', '', '', '']
img_length 0
speaker @user
image_input_length 24
torch.Size([1, 24, 512])
torch.Size([1, 24, 512])
torch.Size([1, 24, 512])
torch.Size([1, 24, 512])
2021-06-03 20:48:21,408 - train.py[line:180] - INFO: Epoch [1], Batch [24], Loss: 9.93677, Perplexity: 20676.80001, Accuracy: 7.692 %
25
530339
img ['', '', '', '', '', '', '', '', '', '', '', '']
img_length 0
speaker @user
image_input_length 12
img ['https://images-na.ssl-images-amazon.com/images/I/51JM8VIHg3L.jpg', '', '', '', '', '', '', '', '', '', '', '']
img_length 1
speaker @system
image_input_length 24
torch.Size([1, 12, 512])
torch.Size([1, 24, 512])
torch.Size([1, 24, 512])
torch.Size([1, 24, 512])
Traceback (most recent call last):
  File "/home/jfhe/Documents/daily software/pycharm/pycharm-professional-anaconda-2019.1.1/pycharm-anaconda-2019.1.1/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/jfhe/Documents/daily software/pycharm/pycharm-professional-anaconda-2019.1.1/pycharm-anaconda-2019.1.1/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/jfhe/Documents/daily software/pycharm/pycharm-professional-anaconda-2019.1.1/pycharm-anaconda-2019.1.1/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/jfhe/Documents/daily software/pycharm/pycharm-professional-anaconda-2019.1.1/pycharm-anaconda-2019.1.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/jfhe/Documents/MountHe/jfhe/mm_dialogue/MM_Dialogue/train.py", line 267, in <module>
    exit(main(_args))
  File "/home/jfhe/Documents/MountHe/jfhe/mm_dialogue/MM_Dialogue/train.py", line 166, in main
    dec_output_prob = model((text_input, text_pos, text_turn, text_speaker,
  File "/home/jfhe/anaconda3/envs/MM20/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jfhe/Documents/MountHe/jfhe/mm_dialogue/MM_Dialogue/widget/model.py", line 83, in forward
    context_embs, context_seq = self.context_encode(context)
  File "/home/jfhe/Documents/MountHe/jfhe/mm_dialogue/MM_Dialogue/widget/model.py", line 88, in context_encode
    text_embs, image_embs = self.emb(text_input, text_pos, text_turn, text_speaker,
  File "/home/jfhe/anaconda3/envs/MM20/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jfhe/Documents/MountHe/jfhe/mm_dialogue/MM_Dialogue/widget/module.py", line 64, in forward
    image_outputs = self.image_layer(image_input) + self.src_token_emb(image_turn) + \
RuntimeError: The size of tensor a (12) must match the size of tensor b (24) at non-singleton dimension 1

**Comment by he159ok** [comment]
Yes, after regenerating the data in the folder called `processed` and `work_path`, it has been run smoothly.
